services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
#   ports:
#     - "8000:8000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
    volumes:
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn stock_prediction_main.wsgi:application --bind 0.0.0.0:8000 --workers 3"
#            python manage.py runserver 0.0.0.0:8000"
             

  frontend:
    build:
      context: ./frontend
      args:
#       VITE_BACKEND_BASE_API: "http://127.0.0.1:8000/api/v1"
#       VITE_BACKEND_BASE_API: "http://104.248.58.250/api/v1"
        VITE_BACKEND_BASE_API: "/api/v1"
#   ports:
#     - "5173:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/static
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend


# This creates a named Docker volume to permanently store PostgreSQL data.
# Without this:
  # Database data is stored inside the container
  # If container is deleted → data is lost
# With this:
  # Data is stored in a Docker-managed volume
  # Data persists even if container stops or restarts
volumes:
  postgres_data: